name: Run

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: results
      - name: Install
        run: npm ci
      - name: Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Runner
        run: deno task tests
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results.json
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: results.json
