name: Run

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Runner
        run: deno task tests
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          commit_message: updates results
